#! /bin/bash
first_print(){
clear
echo `tput setaf 111`"


    ____     ___     ____     __ __    ____    ____    _____   _____   ___
   / __ \   /   |   / __ \   / //_/   / __ )  / __ \  / ___/  / ___/  <  /
  / / / /  / /| |  / /_/ /  / ,<     / __  | / / / /  \__ \   \__ \   / / 
 / /_/ /  / ___ | / _, _/  / /| |   / /_/ / / /_/ /  ___/ /  ___/ /  / /  
/_____/  /_/  |_|/_/ |_|  /_/ |_|  /_____/  \____/  /____/  /____/  /_/   
                                                                          
          ________________________________________________________________________
         |                                                                        |
         |     	             WebSite: serialkey.top                           |
         |	             Creator: darkboss1		          |
         |	             E-mail: chowdhuryethicalhacker@gmail.com		    |
         |							     	          | 
         --------------------------------------------------------------------------
"
}
first_print
sleep .12
echo `tput setaf 202` 'Please select an option :) '
echo ''
sleep .12
echo '[1] Full Scan'
sleep .12
echo ''
echo '[2] Advanced Scan'
sleep .12
echo ''
echo '[3] INFO'
sleep .12
echo ''
read -p' ┌─[your chois]
 └──╼ ' x
case $x in
"1") bash pages/full_scan;;
"2") bash pages/advanced_scan ;;
"3") bash pages/info ;;
esac
